Pulls SetupPrivateTmp, CleanupPrivateTmp, cleanupExit, and hfExit functions from hylafax.org.
git-svn-id: https://svn.code.sf.net/p/hylafax/HylaFAX+@1968 5505949e-d877-4686-9e03-c53b7a51b376

diff --git a/util/common-functions.sh.in b/util/common-functions.sh.in
--- a/util/common-functions.sh.in
+++ b/util/common-functions.sh.in
@@ -1,5 +1,5 @@
 #! @SCRIPT_SH@
-#    $Id: common-functions.sh.in 849 2008-06-18 04:45:01Z faxguy $
+#    $Id: common-functions.sh.in 850 2008-06-18 04:57:58Z faxguy $
 
 #
 # This holds various functions that are common to the
@@ -321,4 +321,52 @@ gs2fax()
     if [ "$DITHERING" = "libtiff-fs" ]; then
 	$RM -f $out.1 $out.2 $out.3
     fi
+}
+
+SetupPrivateTmp()
+{
+    if [ -d "$HYLAFAX_TMPDIR" ]; then
+        # Private temp area already created.
+        return
+    fi
+
+    # Would have liked to use -t, but older mktemp don't support it.
+    if [ -z "$TMPDIR" ]; then
+        TMPDIR="/tmp"
+    fi
+    HYLAFAX_TMPDIR=`mktemp -d $TMPDIR/hylafaxtmp-XXXXXXXX 2>/dev/null` || {
+        HYLAFAX_TMPDIR="$TMPDIR/hylafaxtmp-$RANDOM-$RANDOM-$RANDOM-$$"
+        mkdir -m 0700 "$HYLAFAX_TMPDIR"
+    }
+    if [ $? != 0 ]
+    then
+	echo "Couldn't setup private temp area - exiting!" 1>&2
+	exit 1
+    fi
+    # We want any called programs to use our tmp dir.
+    TMPDIR=$HYLAFAX_TMPDIR
+    export TMPDIR
+
+    trap cleanupExit 0
+    trap "hfExit 1" 1 2 15
+}
+
+CleanupPrivateTmp ()
+{
+    if [ -d "$HYLAFAX_TMPDIR" ]
+    then
+	rm -Rf "$HYLAFAX_TMPDIR"
+    fi
+}
+
+cleanupExit ()
+{
+    trap - 0 1 2 15
+    CleanupPrivateTmp
+}
+
+hfExit ()
+{
+    cleanupExit
+    exit $1
 }
