HylaFAX, Version 4.0pl0 (release)
git-svn-id: https://svn.code.sf.net/p/hylafax/HylaFAX+@4 5505949e-d877-4686-9e03-c53b7a51b376

diff --git a/util/faxcron.sh.in b/util/faxcron.sh.in
--- a/util/faxcron.sh.in
+++ b/util/faxcron.sh.in
@@ -1,12 +1,10 @@
-#! @SCRIPT_SH@
-#	$Header: /usr/people/sam/fax/./util/RCS/faxcron.sh.in,v 1.27 1995/04/08 21:44:49 sam Rel $
-#
-# @WARNING@
+#! /bin/sh
+#	$Id: faxcron.sh.in,v 1.37 1996/06/24 03:06:17 sam Rel $
 #
 # HylaFAX Facsimile Software
 #
-# Copyright (c) 1993-1995 Sam Leffler
-# Copyright (c) 1993-1995 Silicon Graphics, Inc.
+# Copyright (c) 1993-1996 Sam Leffler
+# Copyright (c) 1993-1996 Silicon Graphics, Inc.
 # HylaFAX is a trademark of Silicon Graphics
 # 
 # Permission to use, copy, modify, distribute, and sell this software and 
@@ -30,49 +28,48 @@
 #
 
 #
-# VERSION:	@VERSION@
-# DATE:		@DATE@
-#
-
-#
 # Script to run periodically from cron:
 #
 # 0. Print transmit and receive statistics.
 # 1. Purge info directory of old remote machine capabilities.
-# 2. Truncate log files to delete old information.
+# 2. Purge old session logs from the log directory.
 # 3. Purge old files in the received facsimile queue.
 # 4. Notify about sites that currently have jobs rejected.
 #
-SPOOL=@SPOOL@
-SBIN=@SBIN@
-JUNK=/tmp/faxjunk$$
-AWKTMP=/tmp/faxawk$$
-XFERLOG=$SPOOL/etc/xferlog
-LAST=$SPOOL/etc/lastrun
 
 AGEINFO=30			# purge remote info after 30 days inactivity
 AGELOG=30			# keep log info for last 30 days
 AGERCV=2			# purge received facsimile after 2 days
+AGETMP=1			# purge orphaned temp files after 1 day
 FAXUSER=fax			# owner of log files
 LOGMODE=0644			# mode for log files
+XFERLOG=etc/xferlog		# HylaFAX xferlog file location
+LAST=etc/lastrun		# file where time+date of last run recorded
 
-PATH=/bin:/usr/bin:/etc
-test -d /usr/ucb  && PATH=$PATH:/usr/ucb		# Sun and others
-test -d /usr/bsd  && PATH=$PATH:/usr/bsd		# Silicon Graphics
-test -d /usr/5bin && PATH=/usr/5bin:$PATH:/usr/etc	# Sun and others
-test -d /usr/sbin && PATH=/usr/sbin:$PATH		# 4.4BSD-derived
+cd @SPOOL@			# NB: everything below assumes this
 
-AWK=@AWK@
-RM="@RM@ -f"
+test -f etc/setup.cache || {
+    SPOOL=`pwd`
+    cat<<EOF
+
+FATAL ERROR: $SPOOL/etc/setup.cache is missing!
+
+The file $SPOOL/etc/setup.cache is not present.  This
+probably means the machine has not been setup using the faxsetup(1M)
+command.  Read the documentation on setting up HylaFAX before you
+startup a server system.
+
+EOF
+    exit 1
+}
+. etc/setup.cache
+
+RM="$RM -f"
 TEE=tee
-CP=@CP@
-MV=@MV@
-CHOWN=@CHOWN@
-CHMOD=@CHMOD@
 UPDATE="date +'%D %H:%M' >$LAST"
-SH=@SCRIPT_SH@
-GREP=@GREP@
-CAT=@CAT@
+
+JUNK=/tmp/faxjunk$$		# temp file used multiple times
+AWKTMP=/tmp/faxawk$$		# temp file for awk program
 
 while [ x"$1" != x"" ] ; do
     case $1 in
@@ -81,36 +78,36 @@ while [ x"$1" != x"" ] ; do
     -info)  shift; AGEINFO="$1";;
     -log)   shift; AGELOG="$1";;
     -rcv)   shift; AGERCV="$1";;
+    -tmp)   shift; AGETMP="$1";;
     -mode)  shift; LOGMODE="$1";;
-    -*)	    echo "Usage: $0 [-n] [-l lastrun] [-info days] [-log days] [-rcv days] [-mode logmode]"; exit 1;;
+    -*)	    echo "Usage: $0 [-n] [-l lastrun] [-info days] [-log days] [-rcv days] [-tmp days] [-mode logmode]"; exit 1;;
     esac
     shift
 done
 
 trap "$RM \$AWKTMP \$JUNK; exit 1" 0 1 2 15
 
-cd $SPOOL
 
 test -z "$LASTRUN" && LASTRUN=`$CAT $LAST 2>/dev/null`
 
 echo "Facsimile transmitted since $LASTRUN:"
 echo ""
-$SH $SBIN/xferstats -since "$LASTRUN" 
+$SBIN/xferstats -since "$LASTRUN" 
 echo ""
 
 echo "Facsimile transmitted since last week:"
 echo ""
-$SH $SBIN/xferstats -age 7
+$SBIN/xferstats -age 7
 echo ""
 
 echo "Facsimile received since $LASTRUN:"
 echo ""
-$SH $SBIN/recvstats -since "$LASTRUN" 
+$SBIN/recvstats -since "$LASTRUN" 
 echo ""
 
 echo "Facsimile received since last week:"
 echo ""
-$SH $SBIN/recvstats -age 7
+$SBIN/recvstats -age 7
 echo ""
 
 echo "Report failed calls and associated session logs:"
@@ -144,7 +141,7 @@ function qsort(a, l, r) {
 	qsort(a, k+1, r);
 }
 
-func cleanup(s)
+function cleanup(s)
 {
     gsub("\"", "", s);
     gsub("^ +", "", s);
@@ -152,7 +149,7 @@ func cleanup(s)
     return s;
 }
 
-func setupToLower()
+function setupToLower()
 {
     upperRE = "[ABCDEFGHIJKLMNOPQRSTUVWXYZ]";
     upper["A"] = "a"; upper["B"] = "b"; upper["C"] = "c";
@@ -166,7 +163,7 @@ func setupToLower()
     upper["Y"] = "y"; upper["Z"] = "z";
 }
 
-func toLower(s)
+function toLower(s)
 {
     if (match(s, upperRE) != 0) {
 	do {
@@ -180,7 +177,7 @@ func toLower(s)
 #
 # Accumulate a statistics record.
 #
-func acct(dest, status, datetime)
+function acct(dest, status, datetime, commid)
 {
     split(datetime, a, " ");
     split(a[1], b, "/");
@@ -192,8 +189,6 @@ func acct(dest, status, datetime)
 	msg = toLower(substr(status, 1, 11));
 	if (callFailed[msg])
 	    return;
-	if (skipError[msg])
-	    return;
     }
     if (status != "") {
 	dest = cleanup(dest);
@@ -204,13 +199,13 @@ func acct(dest, status, datetime)
 	if (i == nerrmsg)
 	    errmsg[nerrmsg++] = status;
 	if (errinfo[dest] == "")
-	    errinfo[dest] = datetime "@" i;
+	    errinfo[dest] = datetime "@" i "/" commid;
 	else
-	    errinfo[dest] = errinfo[dest] "|" datetime "@" i;
+	    errinfo[dest] = errinfo[dest] "|" datetime "@" i "/" commid;
     }
 }
 
-func printTranscript(canon, datetime)
+function printOldTranscript(canon, datetime)
 {
     gsub("[^0-9]", "", canon);
     split(datetime, parts, " ");
@@ -219,15 +214,29 @@ func printTranscript(canon, datetime)
     system(cmd);
 }
 
+function printTranscript(commid)
+{
+    printf "\n    ---- Transcript of session follows ----\n\n"
+    comFile = "log/c" commid;
+    if ((getline <comFile) > 0) {
+	do {
+	    if (index($0, "-- data") == 0)
+		print $0
+	} while ((getline <comFile) > 0);
+	close(comFile);
+    } else
+	print "No transcript available.";
+}
+
 BEGIN		{ FS="\t";
 		  callFailed["busy signal"] = 1;
 		  callFailed["unknown pro"] = 1;
 		  callFailed["no carrier "] = 1;
 		  callFailed["no local di"] = 1;
 		  callFailed["no answer f"] = 1;
-		   skipError["job aborted"] = 1;
-		   skipError["invalid dia"] = 1;
-		   skipError["can not loc"] = 1;
+		  callFailed["job aborted"] = 1;
+		  callFailed["invalid dia"] = 1;
+		  callFailed["can not loc"] = 1;
 		  months["01"] = "Jan"; months["02"] = "Feb";
 		  months["03"] = "Mar"; months["04"] = "Apr";
 		  months["05"] = "May"; months["06"] = "Jun";
@@ -240,9 +249,11 @@ BEGIN		{ FS="\t";
 		  LASTt = b[3] b[1] b[2] a[2];
 		  setupToLower();
 		}
-$2 == "SEND" && NF == 9  { acct($4, $9, $1); }
-$2 == "SEND" && NF == 11 { acct($5, $11, $1); }
-$2 == "SEND" && NF == 12 { acct($6, $12, $1); }
+$2 == "SEND" && NF == 9  { acct($4,  $9, $1, ""); }
+$2 == "SEND" && NF == 11 { acct($5, $11, $1, ""); }
+$2 == "SEND" && NF == 12 { acct($6, $12, $1, ""); }
+$2 == "SEND" && NF == 13 { acct($7, $13, $1, $3); }
+$2 == "SEND" && NF == 14 { acct($7, $14, $1, $3); }
 END		{ nsorted = 0;
 		  for (key in errinfo)
 		      sorted[nsorted++] = key;
@@ -251,27 +262,31 @@ END		{ nsorted = 0;
 		      key = sorted[k];
 		      n = split(errinfo[key], a, "|");
 		      for (i = 1; i <= n; i++) {
-			  m = split(a[i], b, "@");
-			  if (m != 2)
+			  if (split(a[i], b, "@") != 2)
+			      continue;
+			  if (split(b[2], d, "/") != 2)
 			      continue;
 			  printf "\n"
 			  printf "To: %-16.16s  Date: %s\n", key, b[1]
-			  printf "Error: %s\n\n", errmsg[b[2]]
+			  printf "Error: %s\n\n", errmsg[d[1]]
 
-			  printTranscript(key, b[1]);
+			  if (d[2] == "")
+			      printOldTranscript(key, b[1]);
+			  else
+			      printTranscript(d[2]);
 		      }
 		  }
 		}
 EOF
 $AWK -f $AWKTMP -v LASTRUN="$LASTRUN" TRANSCRIPT="\
-    LOGFILE=$SPOOL/log/%s;\
+    LOGFILE=log/%s;\
     TMP=/tmp/faxlog\$\$;\
     if [ -f \$LOGFILE ]; then\
-	sed -n -e '/%s %s %s.*SESSION BEGIN/,/SESSION END/p' \$LOGFILE |\
-	sed -e '/start.*timer/d'\
-	    -e '/stop.*timer/d'\
-	    -e '/-- data/d'\
-	    -e 's/^/    /' >\$TMP;\
+	$SED -n -e '/%s %s %s.*SESSION BEGIN/,/SESSION END/p' \$LOGFILE |\
+	$SED -e '/start.*timer/d'\
+	     -e '/stop.*timer/d'\
+	     -e '/-- data/d'\
+	     -e 's/^/    /' >\$TMP;\
     fi;\
     if [ -s \$TMP ]; then\
 	$CAT \$TMP;\
@@ -294,9 +309,9 @@ INFOTMP=info/tmp$$
 for i in `$CAT $JUNK`; do
     if $GREP '^&' $i >/dev/null 2>&1; then
 	echo "    $i (saving locked down values)"
-	sed '/^[^&]/d' $i > $INFOTMP
+	$SED '/^[^&]/d' $i > $INFOTMP
 	$MV $INFOTMP $i; $CHOWN ${FAXUSER} $i; $CHMOD ${LOGMODE} $i
-    else
+    elif [ -f $i ]; then
 	echo "    $i"
 	$RM $i
     fi
@@ -314,13 +329,13 @@ if [ -s $JUNK ]; then
     echo ""
 fi
 
-echo "Truncate session logs older than $AGELOG days:"
+echo "Truncate merged session logs older than $AGELOG days:"
 
 $CAT>$AWKTMP<<'EOF'
 #
 # Setup date conversion data structures.
 #
-func setupDateTimeStuff()
+function setupDateTimeStuff()
 {
     Months["Jan"] =  0; Months["Feb"] =  1; Months["Mar"] =  2;
     Months["Apr"] =  3; Months["May"] =  4; Months["Jun"] =  5;
@@ -339,7 +354,7 @@ func setupDateTimeStuff()
 # Convert MMM DD hh:mm:ss.ms to seconds.
 # NB: this does not deal with leap years.
 #
-func cvtTime(s)
+function cvtTime(s)
 {
     mon = Months[substr(s, 0, 3)];
     yday = substr(s, 5, 2) - 1;
@@ -364,16 +379,18 @@ END			{ print lastRecord }
 EOF
 TODAY="`date +'%h %d %T'`"
 
-for i in log/*; do
-    START=`$AWK -F: -f $AWKTMP -v TODAY="$TODAY" -v AGE=$AGELOG $i` 2>/dev/null
-    if [ "$START" != 1 ]; then
-	sed 1,${START}d $i >$JUNK
-	if [ -s $JUNK ]; then
-	    $MV $JUNK $i; $CHOWN ${FAXUSER} $i; $CHMOD ${LOGMODE} $i
-	    ls -ls $i
-	else
-	    echo "    Remove empty $i"
-	    $RM $i
+for i in log/[0-9]*; do
+    if [ -f $i ]; then
+	START=`$AWK -F: -f $AWKTMP -v TODAY="$TODAY" -v AGE=$AGELOG $i` 2>/dev/null
+	if [ "$START" != 1 ]; then
+	    $SED 1,${START}d $i >$JUNK
+	    if [ -s $JUNK ]; then
+		$MV $JUNK $i; $CHOWN ${FAXUSER} $i; $CHMOD ${LOGMODE} $i
+		ls -ls $i
+	    else
+		echo "    Remove empty $i"
+		$RM $i
+	    fi
 	fi
     fi
 done
@@ -402,6 +419,21 @@ if [ -s $JUNK ]; then
 '
 else
     echo "Nothing to purge in receive queue."
+fi
+echo ""
+
+#
+# Purge old stuff from the temp directory.
+#
+find tmp -mtime +$AGETMP -print >$JUNK
+if [ -s $JUNK ]; then
+    echo "Purge tmp files older than $AGETMP days:"
+    for i in `$CAT $JUNK`; do
+	echo "    Remove $i"
+	$RM $i
+    done
+else
+    echo "Nothing to purge in the tmp directory."
 fi
 echo ""
 
